FROM ubuntu:trusty@sha256:ffc76f71dd8be8c9e222d420dc96901a07b61616689a44c7b3ef6a10b7213de4

RUN apt-get update -y
RUN apt-get install -y curl gcc libc-dev 
#RUN apt-get install -y bsdmainutils gdb git make nasm python

#WORKDIR /root
#RUN git clone https://github.com/longld/peda.git
#RUN echo "source /root/peda/peda.py" >> /root/.gdbinit
#RUN echo 'peda.execute("set breakpoint pending on")' >> /root/peda/peda.py

RUN mkdir -p /opt/polyverse
WORKDIR /opt/polyverse
COPY main.c /opt/polyverse

RUN gcc -fstack-protector-all -fPIC -Fpie -pie -Wl,-z,relro,-z,now -o tcp-echo-server main.c

ENTRYPOINT ["/opt/polyverse/tcp-echo-server"]
