FROM alpine:3.11@sha256:ab00606a42621fb68f2ed6ad3c88be54397f981a7b70a79db3d1172b11c4367d

RUN apk update
RUN apk add bash curl gcc libc-dev
#RUN apk add gdb git make nasm python

#WORKDIR /root
#RUN git clone https://github.com/longld/peda.git
#RUN echo "source /root/peda/peda.py" >> /root/.gdbinit
#RUN echo 'peda.execute("set breakpoint pending on")' >> /root/peda/peda.py

RUN mkdir -p /opt/polyverse
WORKDIR /opt/polyverse
COPY main.c /opt/polyverse

RUN gcc -fstack-protector-all -fPIC -Fpie -pie -Wl,-z,relro,-z,now -o tcp-echo-server main.c

ENTRYPOINT ["/opt/polyverse/tcp-echo-server"]
